#from cohere.classify import Example
from cohere.responses.classify import Example

# sentiment analysis: labels are positive, neutral, negative
sentiment_examples = [
    Example("I am an enthusiastic and dedicated individual who is always eager to take on new challenges and learn new things. I have a strong work ethic and thrive in environments where I can collaborate with others to achieve a common goal. I have a passion for helping others and enjoy volunteering my time to give back to my community. In my free time, I enjoy reading, traveling, and spending time with my family and friends.", "positive"), 
    Example("I am a professional with a diverse range of experiences and skills. I have worked in various industries and have developed a strong understanding of how to be successful in different environments. I am detail-oriented and organized, and I am able to prioritize tasks effectively to ensure timely completion. Outside of work, I enjoy pursuing my hobbies and spending time with my loved ones.", "neutral"), 
    Example("Honestly, there's not much to tell. I'm just another person trying to get by. I've had my fair share of setbacks and challenges, but I try to stay optimistic and keep pushing forward. I wouldn't say that I have any particular talents or standout qualities, but I do my best to work hard and contribute to the team. In my free time, I usually just watch TV or play video games to relax.", "negative"), 
    Example("One time, I had a disagreement with a teammate about the best approach to take on a project. Rather than letting the conflict escalate, I scheduled a meeting with my teammate to discuss our different perspectives and find a compromise. We were both able to voice our opinions and come to a mutually beneficial solution that helped move the project forward.", "positive"), 
    Example("In the past, I have encountered conflicts with teammates on various projects. I typically try to address these conflicts by opening a dialogue with my teammate to discuss the issue and find a resolution. I believe it's important to keep communication lines open and work collaboratively to achieve a common goal.", "neutral"), 
    Example("I've had my fair share of conflicts with teammates in the past, and it's always a frustrating experience. Usually, I try to avoid confrontation and just work around the issue, which may not always be the best approach. There was one time when a teammate and I had a disagreement about how to approach a project, and things got heated. We both ended up digging our heels in, and it took a while for us to find a resolution. Looking back, I wish I had been more proactive about addressing the conflict and finding a solution sooner.", "negative"), 
    Example("There was a time when my team was working on a project with a tight deadline. The team was feeling overwhelmed, and it was clear that we needed to adjust our approach. I took the initiative to lead a brainstorming session where we identified key priorities and developed a new plan of action. I delegated tasks and kept everyone on track, while also providing support and encouragement along the way. Thanks to my leadership, we were able to complete the project ahead of schedule and exceed expectations.", "positive"), 
    Example("I've had several opportunities to demonstrate leadership skills throughout my career. One example that comes to mind is when I had to step up and lead a team during a busy period. I organized the workload, delegated tasks, and provided guidance where necessary. By doing so, we were able to work efficiently and effectively to achieve our goals.", "neutral"), 
    Example("To be honest, I haven't had many opportunities to demonstrate leadership skills in my career. There was one time when my team was struggling to meet a deadline, and I felt like we needed more direction. I tried to step up and take charge, but I didn't have the confidence or experience to do so effectively. Looking back, I wish I had been better prepared and more proactive in taking on a leadership role.", "negative"), 
    Example("One time, I received a call from a customer who was frustrated with an issue they were having. Rather than getting defensive or dismissive, I actively listened to their concerns and empathized with their situation. I then took ownership of the problem and worked collaboratively with my team to find a resolution that satisfied the customer. I followed up with the customer to ensure they were pleased with the outcome, and they expressed their gratitude for my efforts.", "positive"), 
    Example("As part of my job, I regularly interact with customers and strive to provide excellent service. One example that comes to mind is when a customer had a question about a product we offered. I provided a thorough explanation and addressed all their concerns, which ultimately led to them making a purchase. I then followed up with the customer to ensure they were satisfied with their purchase and the service they received.", "neutral"), 
    Example("Honestly, there have been times when it was challenging to please a customer. One time, a customer had a complaint about a product they received, but I didn't have the authority to make things right on the spot. I apologized for the inconvenience and escalated the issue to my supervisor, but the customer was still unhappy with the outcome. Despite my best efforts, I wasn't able to satisfy the customer's expectations, which was disappointing.", "negative"), 
    Example("There was a time when I was presenting at a conference, and the audio-visual equipment malfunctioned. Rather than panicking or getting flustered, I took a deep breath and thought on my feet. I quickly adjusted my presentation to accommodate the technical difficulties and engaged the audience by asking questions and facilitating discussion. By doing so, I was able to turn a potential disaster into a successful and memorable presentation.", "positive"), 
    Example("As part of my job, I encounter situations where I have to think on my feet regularly. One example that comes to mind is when a client unexpectedly requested a change to their project requirements. Rather than delaying the project or pushing back, I worked with my team to come up with a solution that accommodated the change while still meeting the project's deadlines.", "neutral"), 
    Example("There have been times when I've had to think on my feet, but it hasn't always gone smoothly. One time, I was presenting to a group of stakeholders, and one of them asked a question that I wasn't prepared to answer. I stumbled and gave a vague response, which didn't instill confidence in the audience. Looking back, I wish I had been better prepared and more confident in my ability to think on my feet in that situation.", "negative"),
    Example("My proudest professional accomplishment was when I led a team that developed and implemented a new software system for our company. I was responsible for managing the project from start to finish, and I worked closely with stakeholders and team members to ensure the system met all requirements. The project was completed on time and within budget, and it resulted in significant improvements in efficiency and productivity for the company.", "positive"),
    Example("I've had several professional accomplishments that I'm proud of, but one that stands out is when I was recognized by my supervisor for consistently exceeding expectations in my role. I was given additional responsibilities and opportunities for growth, which helped me to develop new skills and advance in my career.", "neutral"),
    Example("To be honest, I'm not sure that I have a specific accomplishment that stands out as my proudest. While I've had successes in my career, I always strive to learn and grow, so I tend to focus more on what I can do better in the future rather than what I've accomplished in the past.", "negative")
]

# word choice: labels are casual (slang, filler words), neutral, and professional
word_choice_examples = [
    Example("I am a results-driven professional with several years of experience in the industry. Throughout my career, I have demonstrated a commitment to customer service and have consistently delivered sales targets on time. I have a proven track record of strong communication and am always looking for opportunities to further develop my skills and expertise.", "professional"), 
    Example("I have 2 years of experience in customer service, and I have gained a solid understanding of communication. In my current/previous role, I have worked on projects that have helped me develop my skills in time management. I am always looking for opportunities to learn and grow professionally.", "neutral"),
    Example("Hey there, I'm Bob, and I've been working in customer service for 2 years. I've had the chance to work on some cool projects that have helped me develop my skills in time management. I'm always looking for new opportunities to learn and grow, and I'm excited to see where my career takes me next.", "casual"),
    Example("In my previous role, I faced a conflict with a teammate regarding the approach we should take on a project. To address the issue, I scheduled a one-on-one meeting with my teammate to understand their perspective and clarify my own. Through active listening and open communication, we were able to identify common goals and agree on a mutually beneficial approach that satisfied both of us. As a result, we were able to complete the project on time and with high-quality results.", "professional"),
    Example("I once had a conflict with a teammate on a project. We had different ideas on how to proceed, which created some tension between us. To resolve the issue, we scheduled a meeting to discuss our perspectives and work together to find a solution. We came up with a compromise that satisfied both of us and allowed us to move forward with the project successfully.", "neutral"),
    Example("I remember one time when me and my teammate were butting heads over how to tackle a project. We were both really passionate about our ideas, but it was causing some friction between us. So, we decided to grab some coffee and talk things out. We were able to find a compromise that worked for both of us, and we finished the project with no issues.", "casual"),
    Example("In my previous role, I was leading a project team that was struggling to meet a tight deadline. To motivate and guide the team towards success, I stepped up and demonstrated my leadership skills by delegating tasks, providing guidance, and setting clear expectations. By leading by example, communicating effectively, and being adaptable to changes, I was able to help the team complete the project on time and with high-quality results.", "professional"),
    Example("I have had several opportunities in my career to demonstrate my leadership skills. One instance that comes to mind was when I was working on a project with a team that was facing some obstacles. To help the team overcome these challenges, I took on a more proactive role by providing direction, support, and encouragement. Through my actions and communication, I was able to help the team achieve their goals and complete the project successfully.", "neutral"),
    Example("I had to step up and be a leader when my team was struggling to get things done. I helped them stay motivated by giving them clear goals and providing guidance along the way. It wasn't always easy, but we managed to pull through and finish the project on time.", "casual"),
    Example("As a customer service representative in my previous role, I received a call from a customer who was upset about a recent billing issue. To ensure the customer was pleased with our service, I actively listened to their concerns, empathized with their frustration, and took ownership of the issue. I provided timely updates on the progress of their case and worked with my team to find a resolution that satisfied the customer. By following up with the customer after the issue was resolved, I ensured their satisfaction and helped to maintain a positive relationship with them.", "professional"),
    Example("I have had numerous instances where I made sure a customer was satisfied with our service. One particular instance was when a customer contacted us regarding a billing issue. I was able to communicate effectively with the customer, address their concerns, and work with my team to resolve the issue in a timely manner. By providing updates and following up with the customer, I ensured that they were pleased with our service.", "neutral"),
    Example("I remember one time when a customer was really upset about a billing issue. I made sure to listen to their complaints and worked with my team to fix the problem. I kept them in the loop and checked back in to make sure they were happy with how we handled things. It ended up being all good!", "casual"),
    Example("During a client presentation, I was asked an unexpected question that required me to think on my feet. Without hesitation, I took a moment to gather my thoughts, provided a concise answer, and backed up my response with relevant data and examples. By being quick-witted and well-prepared, I was able to demonstrate my adaptability and problem-solving skills in front of the client.", "professional"),
    Example("I have had numerous instances where I needed to think on my feet. One particular instance was during a client meeting where I was asked a question that required a quick response. I was able to take a moment to gather my thoughts and provide a clear and concise answer that satisfied the client. By being able to adapt and think on my feet, I was able to maintain a professional image and handle unexpected situations effectively.", "neutral"),
    Example("There was this one time when I was in a meeting and got hit with a question I wasn't prepared for. But I didn't let it throw me off, I took a deep breath and came up with a quick answer that ended up being spot on. It was a bit nerve-wracking, but I was able to think on my feet and handle the situation.", "casual"),
    Example("One of my proudest professional accomplishments was successfully leading a team of individuals to complete a complex project within a tight deadline. This involved coordinating different departments, assigning tasks and responsibilities, monitoring progress, and ensuring that the final outcome met the client's requirements. Through effective communication, strong leadership skills, and attention to detail, I was able to exceed expectations and deliver a high-quality result that received positive feedback from both the client and senior management.", "professional"),
    Example("I have had several accomplishments in my professional career that I am proud of, but one that stands out is leading a team to complete a challenging project within a limited time frame. This involved delegating tasks, tracking progress, and coordinating with different departments to ensure that everything was on track. Despite some unforeseen setbacks, we were able to overcome them and complete the project on time, which received positive feedback from both the client and my supervisor.", "neutral"),
    Example("Man, there was this one project that I totally nailed. It was crazy difficult and we had a tight deadline, but I led the team like a boss and we pulled it off. I had to juggle a ton of tasks and communicate with different departments, but we got it done on time and the client loved it. It was a huge win and definitely one of my proudest moments in my career.", "casual")
]

clarity_examples = [
    Example("Sure, I'd be happy to tell you about myself. I'm a recent graduate with a degree in marketing, and I've spent the past year working in a marketing agency. I'm passionate about digital marketing, especially social media campaigns, and have worked on several successful campaigns for clients. In my free time, I enjoy hiking and trying out new recipes in the kitchen.", "clear"),
    Example("Well, I'm a recent college grad with a degree in marketing, and I've been working at a marketing agency for about a year now. I really enjoy working on digital marketing campaigns, specifically social media. Outside of work, I like to stay active and enjoy hiking and cooking.", "neutral"),
    Example("Uh, well, let's see. I just graduated from college with a degree in marketing, and I've been working at a marketing agency for like a year now. I really like digital marketing, especially social media stuff. And, um, when I'm not working, I like to, like, go hiking and cook, and stuff like that.", "unclear"),
    Example("One time, during my previous job, our team was working on a project that required us to use a specific software tool that I was not familiar with. We were on a tight deadline and the rest of the team was busy with other tasks, so I took it upon myself to learn the software and complete the task. I spent several hours researching and experimenting with the tool until I became proficient enough to use it effectively. In the end, I was able to complete the task on time, and my team was impressed with my resourcefulness and dedication.", "clear"),
    Example("Well, there was this one time when I was working on a project and we had to use this software tool that I wasn't really familiar with. The rest of the team was busy, so I decided to take it upon myself to learn the software and complete the task. It took me a while, but I was eventually able to figure it out and complete the task on time.", "neutral"),
    Example("Uh, well, like, there was this project I was working on, and we had to use this software thing that I didn't really know how to use. The rest of the team was busy, so I had to figure it out on my own. It was kind of hard and took me a while, but I eventually figured it out and got the task done on time, I guess.", "unclear"),
    Example("I had a difficult colleague in my previous job who often showed up late to meetings and failed to deliver on their assigned tasks. To address the issue, I scheduled a one-on-one meeting with them to discuss the problem and offer my help. During the meeting, I listened to their concerns and tried to understand the root cause of their behavior. We agreed on specific steps to improve their performance and established a clear communication plan moving forward. Although it wasn't easy, I was able to effectively work with my colleague and improve our working relationship.", "clear"),
    Example("In my previous job, I worked with a colleague who was challenging to work with. They often missed deadlines and were not contributing to the team's success. I addressed the issue by having a one-on-one meeting with them, where we discussed their concerns and worked together to develop a plan to improve their performance. After that, we established a clear communication plan and were able to work better together.", "neutral"),
    Example("Uh yeah, I had a colleague in my previous job who was, like, super difficult to work with. They were always late to meetings and didn't deliver their work on time. So, I, um, talked to them and tried to understand what was going on, and we, like, made a plan to improve their performance. And, yeah, it wasn't easy, but we, like, improved our working relationship.", "unclear"),
    Example("In my previous job, our team was suddenly tasked with a new project that required a different set of skills than what we were used to. I took the initiative to research and learn about the new skills required, and also volunteered to attend a training session to gain further knowledge. I then shared my findings with the team and worked with them to create a plan to successfully complete the project. Through this experience, I was able to adapt to a new situation and contribute to the team's success.", "clear"),
    Example("During my previous job, our team was assigned to work on a new project that required us to learn new skills. I researched and attended a training session to gain the necessary knowledge, and then shared my findings with the team. Together, we were able to adapt to the new situation and complete the project successfully.", "neutral"),
    Example("Yeah, so in my old job, we got this new project that was, like, totally different from what we usually did. I had to figure out some new skills and stuff, so I, uh, did some research and went to a training session. And then, like, I shared what I learned with the team and we, um, managed to complete the project.", "unclear"),
    Example("During my last job, I had to make a difficult decision about whether or not to terminate an underperforming employee. I carefully reviewed their performance metrics and discussed the situation with my supervisor to gain additional insights. I also had a one-on-one meeting with the employee to discuss their performance and give them feedback. Ultimately, I decided to terminate their employment, as their performance was not meeting the expectations of the company. Although it was a tough decision, it was necessary for the company's success.", "clear"),
    Example("In my previous job, I had to make a difficult decision regarding an employee's performance. I reviewed their metrics, discussed the situation with my supervisor, and had a meeting with the employee to give feedback. After careful consideration, I decided to terminate their employment.", "neutral"),
    Example("So, yeah, I had to make a tough decision at my old job about this employee who wasn't doing so well. I, uh, looked at their performance stuff and talked to my boss and had a meeting with the employee. And, yeah, I decided to, like, fire them in the end.", "unclear"),
    Example("I worked on a design project for a client where they wanted a unique and creative approach for their product packaging. I spent time researching and understanding the product, the brand and the target audience. I came up with several concepts and presented them to the client. The client chose one of my designs, and I then worked with a team to refine the design, select the right colors, and create prototypes. The final product was very well received, and the client was happy with our work.", "clear"),
    Example("One project that required me to use my creativity was a design project for a client's product packaging. I spent time researching and came up with several concepts, which the client liked. We then refined the design and created prototypes.", "neutral"),
    Example("I had a project where I had to use my creativity. It was for a client's packaging design or something. I researched and came up with some ideas, and the client liked one. We worked on it and made it look nice.", "unclear")
]


#structure: labels are structured, neutral, unstructured
structure_examples = [
    Example("During my previous role at Company X, we had a project with an urgent deadline to deliver a new product feature. I was tasked with coordinating the efforts of a cross-functional team. To manage the tight timeline, I created a detailed project plan with milestones and assigned specific tasks to each team member. I ensured open communication channels, tracked progress regularly, and addressed any roadblocks swiftly. As a result, we successfully delivered the feature ahead of schedule, satisfying both customers and stakeholders.", "structured"),
    Example("At my previous job, we had a disagreement between two team members about the direction of a project. I stepped in to mediate the situation and find a resolution. I scheduled a private meeting with both individuals to understand their perspectives and concerns. We discussed potential compromises and collaborated on a revised project plan that incorporated elements from both viewpoints. This improved collaboration led to smoother project execution and a more positive team dynamic.", "structured"),
    Example("In my role at Company Y, we encountered unexpected changes in client requirements midway through a project. The project scope had to be revised, and new features had to be integrated. I quickly organized a team meeting to discuss the changes and allocated tasks based on individual strengths. We adjusted our timeline, worked overtime when necessary, and maintained open communication with the client. Ultimately, we successfully incorporated the changes while minimizing any negative impact on project timelines and quality.", "structured"),
    Example("During a team-building workshop at my previous job, we were struggling to come up with innovative ideas for a new marketing campaign. I recognized the need for strong leadership to inspire creativity and collaboration. I took the initiative to facilitate brainstorming sessions, encouraging everyone to contribute their ideas. By fostering an open environment, we generated numerous creative concepts and were able to select an exciting campaign direction that received positive feedback from both colleagues and clients.", "structured"),
    Example("At my retail job, a customer was unhappy with a product they purchased due to a defect. I empathized with the customer's frustration and took ownership of the situation. I offered them a replacement product and explained the return process. Additionally, I reported the issue to our quality control team to prevent similar incidents in the future. The customer left the store satisfied with our solution and even left a positive review praising our customer service.", "structured"),
    Example("During a software development project at my previous job, we encountered unexpected technical hurdles that threatened the project's success. Our team was tasked with developing a complex application within a tight timeline. I organized regular meetings to brainstorm solutions with my team members. We conducted thorough research, collaborated closely with our technical experts, and adjusted our development approach. As a result of our collective efforts, we overcame the challenges, delivered a high-quality product, and gained valuable insights for future projects.", "structured"),
    Example("At my internship, I had to balance coursework, a part-time job, and an extracurricular project. With various commitments demanding my attention, effective time management became crucial. I created a detailed schedule that allocated specific time blocks for each activity and prioritized tasks based on deadlines. I used productivity techniques like the Pomodoro method to maintain focus during study sessions and efficiently complete tasks. Despite the demanding workload, I successfully maintained my grades, fulfilled work obligations, and contributed significantly to the extracurricular project.", "structured"),
    Example("During a team meeting at my previous job, I proposed a new approach to streamline our project management process. Some team members were skeptical about the potential benefits of this change. I prepared a detailed presentation that outlined the advantages of the proposed approach, addressing their concerns. I encouraged an open discussion, listened to their feedback, and provided real-life examples of successful implementations from other companies. As a result, I gained their support, and we implemented the new process, which led to improved efficiency and more organized project execution.", "structured"),
    Example("During a client project at my previous job, I was tasked with creating a data visualization using a software tool I had never used before. This tool was essential for presenting our findings effectively. I recognized the need to learn the software quickly. I dedicated extra hours to self-paced learning, watching tutorials, experimenting with the tool, and seeking help from colleagues who were experienced with it. As a result of my efforts, I successfully created the data visualization within the project's timeline and exceeded the client's expectations with the quality of the presentation.", "structured"),
    Example("In a group project during my university studies, I encountered a team member who was consistently uncooperative and resistant to collaboration. To ensure project success, I needed to find a way to work effectively with this individual. I approached them privately to discuss their concerns and find common ground. I actively listened to their perspective, offered assistance, and identified areas where their expertise could be valuable. Over time, our communication improved, and they started to contribute positively to the project. As a result, we were able to complete the project on time and deliver high-quality work despite the initial challenges.", "structured"),
    Example("There was this customer who was really mad about our product. I tried to calm them down and explain the situation. I think they were upset about the shipping delay. I talked to my manager about it, and we eventually got the issue resolved.", "unstructured"),
    Example("Well, in my last job, I kind of took charge of a project. It was a big project and my team needed guidance. So, I stepped up and helped everyone stay on track. We finished the project and it went pretty well.", "unstructured"),
    Example("I once had to work on a team with people from different backgrounds. We had some disagreements, but we managed to get things done. We all had different ideas about how to approach the project.", "unstructured"),
    Example("I had a problem at work that I had to solve. It was hard at first, but I kept trying different things until I found a solution. It took some time, but I eventually figured it out.", "unstructured"),
    Example("At my last job, things changed suddenly, and I had to adapt. It was kind of stressful, but I managed to adjust and do what I needed to do. It was a bit tough, but I got through it.", "unstructured"),
    Example("I worked on a group project in college where we had to create a presentation together. I collaborated with my team members, shared ideas, and helped with the research. We all presented different parts of the project and received positive feedback from our classmates.", "neutral"),
    Example("In my last job, I had to manage a tight deadline for a client project. It was difficult, but I organized the tasks, assigned them to team members, and we all worked hard to complete it on time. We finished the project, and the client seemed satisfied with the result", "neutral"),
    Example("Once, a customer was unhappy with our service. I talked to them, listened to their concerns, and tried to resolve the issue. It was a bit tense, but we managed to reach a solution, and the customer left without any major complaints.", "neutral"),
    Example("At my previous job, I was in charge of a project. I provided direction to the team, made decisions, and communicated with stakeholders. The project was completed, and we met our goals.", "neutral"),
    Example("In my current role, there was a change in our procedures. It was challenging, but I adjusted my workflow, learned the new process, and continued to meet my targets.", "neutral"),
]

#specific: labes are specific, neutral, generic
specific_examples = [
    Example("In my previous job, we faced a situation where our project was falling behind schedule due to unexpected technical challenges. I took the initiative to analyze the issue, collaborating closely with our development team. We identified the root cause, developed a workaround, and implemented it promptly. As a result, we not only met the original deadline but also improved the efficiency of our development process, saving valuable time on future projects", "specific"),
    Example("During my internship, I had to juggle coursework, my internship responsibilities, and involvement in a student organization. Once, a major assignment coincided with a critical project deadline. To handle this, I organized my time meticulously, communicated with both my professor and supervisor, and delegated some tasks within the student organization. By managing my time effectively and collaborating with others, I successfully completed the assignment and delivered quality work for my internship and student involvement.", "specific"),
    Example("In my university's engineering competition, I was part of a team tasked with building a complex prototype. I collaborated closely with my teammates, leveraging each individual's strengths. For instance, I took charge of coordinating communication between sub-teams, ensuring everyone was aligned on goals. This efficient coordination allowed us to meet our milestones ahead of schedule, and our prototype garnered high praise from judges, securing us a top position in the competition.", "specific"),
    Example("At my part-time job, our department was undergoing a transition to a new software system. Recognizing that this change could be daunting for some colleagues, I took the lead in organizing training sessions. I designed comprehensive training materials, conducted hands-on workshops, and provided one-on-one support to those struggling. As a result, our team smoothly transitioned to the new system, and the feedback I received highlighted the clarity and effectiveness of my leadership in facilitating this change.", "specific"),
    Example("During my time as a project manager, we were tasked with organizing a large-scale charity event with a limited budget. To overcome this challenge, I leveraged my negotiation skills to secure sponsorships and in-kind donations. I also implemented a meticulous budget tracking system to ensure we stayed within our financial constraints. Through these efforts, we not only delivered a successful event that exceeded our goals but also raised more funds for the charity than anticipated, showcasing my effective project management abilities.", "specific"),
    Example("At my retail job, a customer had a specific request for a product that wasn't in stock. I took the initiative to research alternative options and found a similar product from another branch. I arranged for it to be shipped to our store, personally followed up with the customer to ensure their satisfaction, and even offered a discount for the inconvenience. The customer was genuinely impressed by the level of personalized service and wrote a positive review highlighting my dedication to meeting their needs.", "specific"),
    Example("In my previous role, I had to lead a project with team members across different time zones. To ensure clear communication, I set up a structured weekly video call where we discussed progress, challenges, and action items. For instance, during a critical phase, we had a team member facing technical difficulties. I quickly organized a troubleshooting session via video call, guiding them step-by-step to resolve the issue. This proactive approach streamlined our communication and kept the project on track.", "neutral"),
    Example("During my internship, we had a sudden surge in customer inquiries due to a product launch. I was responsible for customer support and encountered a particularly complex issue that required immediate attention. While handling routine inquiries, I also tackled this complex case by staying focused, conducting thorough research, and collaborating with the technical team. Despite the pressure, I managed to resolve the issue within the expected timeframe, ensuring customer satisfaction", "neutral"),
    Example("At my previous job, we were implementing a new software system, and I was assigned to lead the training sessions. However, on the day of the training, the software crashed unexpectedly. To adapt, I quickly switched to a backup plan, using printed materials and interactive discussions to convey the information effectively. Despite the technical hiccup, the training was well-received, and attendees commended my ability to adapt to unexpected challenges", "neutral"),
    Example("During a university research project, I had to analyze a large dataset to identify trends and insights. The data was disorganized and required extensive cleaning before analysis. I meticulously sorted and cleaned the data using advanced Excel functions and data visualization tools. Despite spending several extra hours, my efforts paid off—I uncovered a significant pattern that contributed valuable insights to our research, earning praise from my professor.", "neutral"),
    Example("In a team meeting at my previous job, we were debating the direction of a marketing campaign. I believed a more interactive approach would resonate better with our target audience. I presented a detailed plan, backed by research from similar successful campaigns. Despite initial skepticism, I engaged my colleagues in a discussion, addressing their concerns and demonstrating the potential impact of the interactive approach. Gradually, they embraced the idea, and the resulting campaign generated higher engagement and conversion rates.", "neutral"),
    Example("During a quality control project, I was responsible for reviewing a large batch of documents for accuracy. While reviewing, I noticed a discrepancy in a crucial formula that could have led to errors in the final product. I flagged the issue to my supervisor, and after further investigation, we discovered a formatting error that affected multiple documents. My attention to detail prevented potential costly mistakes and demonstrated my commitment to maintaining high standards", "neutral"),
    Example("In a previous job, I encountered a problem and had to come up with a solution. I analyzed the situation, thought critically, and took steps to resolve it. Eventually, I found a solution that worked.", "generic"),
    Example("I've been part of various teams in my career, and I always collaborated effectively. We communicated, shared ideas, and completed tasks together.", "generic"),
    Example("Change is a part of any job. I've had to adapt to changes in processes and procedures, and I always find a way to adjust.", "generic"),
    Example("Challenges come up in every job. I faced a challenge once and used my skills to overcome it. It wasn't easy, but I managed to find a solution.", "generic"),
    Example("Leadership is important, and I've had instances where I had to lead a team. I provided guidance and direction, and we achieved our goals", "generic"),
    Example("Difficult situations happen in every workplace. I once had a difficult situation, and I managed it by staying calm and addressing the issue.", "generic"),
]

#relevance
#quantitive achievemnts
#highlight skills


