from cohere.classify import Example

# sentiment analysis: labels are positive, neutral, negative
sentiment_examples = [
    Example("I am an enthusiastic and dedicated individual who is always eager to take on new challenges and learn new things. I have a strong work ethic and thrive in environments where I can collaborate with others to achieve a common goal. I have a passion for helping others and enjoy volunteering my time to give back to my community. In my free time, I enjoy reading, traveling, and spending time with my family and friends.", "positive"), 
    Example("I am a professional with a diverse range of experiences and skills. I have worked in various industries and have developed a strong understanding of how to be successful in different environments. I am detail-oriented and organized, and I am able to prioritize tasks effectively to ensure timely completion. Outside of work, I enjoy pursuing my hobbies and spending time with my loved ones.", "neutral"), 
    Example("Honestly, there's not much to tell. I'm just another person trying to get by. I've had my fair share of setbacks and challenges, but I try to stay optimistic and keep pushing forward. I wouldn't say that I have any particular talents or standout qualities, but I do my best to work hard and contribute to the team. In my free time, I usually just watch TV or play video games to relax.", "negative"), 
    Example("One time, I had a disagreement with a teammate about the best approach to take on a project. Rather than letting the conflict escalate, I scheduled a meeting with my teammate to discuss our different perspectives and find a compromise. We were both able to voice our opinions and come to a mutually beneficial solution that helped move the project forward.", "positive"), 
    Example("In the past, I have encountered conflicts with teammates on various projects. I typically try to address these conflicts by opening a dialogue with my teammate to discuss the issue and find a resolution. I believe it's important to keep communication lines open and work collaboratively to achieve a common goal.", "neutral"), 
    Example("I've had my fair share of conflicts with teammates in the past, and it's always a frustrating experience. Usually, I try to avoid confrontation and just work around the issue, which may not always be the best approach. There was one time when a teammate and I had a disagreement about how to approach a project, and things got heated. We both ended up digging our heels in, and it took a while for us to find a resolution. Looking back, I wish I had been more proactive about addressing the conflict and finding a solution sooner.", "negative"), 
    Example("There was a time when my team was working on a project with a tight deadline. The team was feeling overwhelmed, and it was clear that we needed to adjust our approach. I took the initiative to lead a brainstorming session where we identified key priorities and developed a new plan of action. I delegated tasks and kept everyone on track, while also providing support and encouragement along the way. Thanks to my leadership, we were able to complete the project ahead of schedule and exceed expectations.", "positive"), 
    Example("I've had several opportunities to demonstrate leadership skills throughout my career. One example that comes to mind is when I had to step up and lead a team during a busy period. I organized the workload, delegated tasks, and provided guidance where necessary. By doing so, we were able to work efficiently and effectively to achieve our goals.", "neutral"), 
    Example("To be honest, I haven't had many opportunities to demonstrate leadership skills in my career. There was one time when my team was struggling to meet a deadline, and I felt like we needed more direction. I tried to step up and take charge, but I didn't have the confidence or experience to do so effectively. Looking back, I wish I had been better prepared and more proactive in taking on a leadership role.", "negative"), 
    Example("One time, I received a call from a customer who was frustrated with an issue they were having. Rather than getting defensive or dismissive, I actively listened to their concerns and empathized with their situation. I then took ownership of the problem and worked collaboratively with my team to find a resolution that satisfied the customer. I followed up with the customer to ensure they were pleased with the outcome, and they expressed their gratitude for my efforts.", "positive"), 
    Example("As part of my job, I regularly interact with customers and strive to provide excellent service. One example that comes to mind is when a customer had a question about a product we offered. I provided a thorough explanation and addressed all their concerns, which ultimately led to them making a purchase. I then followed up with the customer to ensure they were satisfied with their purchase and the service they received.", "neutral"), 
    Example("Honestly, there have been times when it was challenging to please a customer. One time, a customer had a complaint about a product they received, but I didn't have the authority to make things right on the spot. I apologized for the inconvenience and escalated the issue to my supervisor, but the customer was still unhappy with the outcome. Despite my best efforts, I wasn't able to satisfy the customer's expectations, which was disappointing.", "negative"), 
    Example("There was a time when I was presenting at a conference, and the audio-visual equipment malfunctioned. Rather than panicking or getting flustered, I took a deep breath and thought on my feet. I quickly adjusted my presentation to accommodate the technical difficulties and engaged the audience by asking questions and facilitating discussion. By doing so, I was able to turn a potential disaster into a successful and memorable presentation.", "positive"), 
    Example("As part of my job, I encounter situations where I have to think on my feet regularly. One example that comes to mind is when a client unexpectedly requested a change to their project requirements. Rather than delaying the project or pushing back, I worked with my team to come up with a solution that accommodated the change while still meeting the project's deadlines.", "neutral"), 
    Example("There have been times when I've had to think on my feet, but it hasn't always gone smoothly. One time, I was presenting to a group of stakeholders, and one of them asked a question that I wasn't prepared to answer. I stumbled and gave a vague response, which didn't instill confidence in the audience. Looking back, I wish I had been better prepared and more confident in my ability to think on my feet in that situation.", "negative"),
    Example("My proudest professional accomplishment was when I led a team that developed and implemented a new software system for our company. I was responsible for managing the project from start to finish, and I worked closely with stakeholders and team members to ensure the system met all requirements. The project was completed on time and within budget, and it resulted in significant improvements in efficiency and productivity for the company.", "positive"),
    Example("I've had several professional accomplishments that I'm proud of, but one that stands out is when I was recognized by my supervisor for consistently exceeding expectations in my role. I was given additional responsibilities and opportunities for growth, which helped me to develop new skills and advance in my career.", "neutral"),
    Example("To be honest, I'm not sure that I have a specific accomplishment that stands out as my proudest. While I've had successes in my career, I always strive to learn and grow, so I tend to focus more on what I can do better in the future rather than what I've accomplished in the past.", "negative")
]

# word choice: labels are casual (slang, filler words), neutral, and professional
word_choice_examples = [
    Example("I am a results-driven professional with several years of experience in the industry. Throughout my career, I have demonstrated a commitment to customer service and have consistently delivered sales targets on time. I have a proven track record of strong communication and am always looking for opportunities to further develop my skills and expertise.", "professional"), 
    Example("I have 2 years of experience in customer service, and I have gained a solid understanding of communication. In my current/previous role, I have worked on projects that have helped me develop my skills in time management. I am always looking for opportunities to learn and grow professionally.", "neutral"),
    Example("Hey there, I'm Bob, and I've been working in customer service for 2 years. I've had the chance to work on some cool projects that have helped me develop my skills in time management. I'm always looking for new opportunities to learn and grow, and I'm excited to see where my career takes me next.", "casual"),
    Example("In my previous role, I faced a conflict with a teammate regarding the approach we should take on a project. To address the issue, I scheduled a one-on-one meeting with my teammate to understand their perspective and clarify my own. Through active listening and open communication, we were able to identify common goals and agree on a mutually beneficial approach that satisfied both of us. As a result, we were able to complete the project on time and with high-quality results.", "professional"),
    Example("I once had a conflict with a teammate on a project. We had different ideas on how to proceed, which created some tension between us. To resolve the issue, we scheduled a meeting to discuss our perspectives and work together to find a solution. We came up with a compromise that satisfied both of us and allowed us to move forward with the project successfully.", "neutral"),
    Example("I remember one time when me and my teammate were butting heads over how to tackle a project. We were both really passionate about our ideas, but it was causing some friction between us. So, we decided to grab some coffee and talk things out. We were able to find a compromise that worked for both of us, and we finished the project with no issues.", "casual"),
    Example("In my previous role, I was leading a project team that was struggling to meet a tight deadline. To motivate and guide the team towards success, I stepped up and demonstrated my leadership skills by delegating tasks, providing guidance, and setting clear expectations. By leading by example, communicating effectively, and being adaptable to changes, I was able to help the team complete the project on time and with high-quality results.", "professional"),
    Example("I have had several opportunities in my career to demonstrate my leadership skills. One instance that comes to mind was when I was working on a project with a team that was facing some obstacles. To help the team overcome these challenges, I took on a more proactive role by providing direction, support, and encouragement. Through my actions and communication, I was able to help the team achieve their goals and complete the project successfully.", "neutral"),
    Example("I had to step up and be a leader when my team was struggling to get things done. I helped them stay motivated by giving them clear goals and providing guidance along the way. It wasn't always easy, but we managed to pull through and finish the project on time.", "casual"),
    Example("As a customer service representative in my previous role, I received a call from a customer who was upset about a recent billing issue. To ensure the customer was pleased with our service, I actively listened to their concerns, empathized with their frustration, and took ownership of the issue. I provided timely updates on the progress of their case and worked with my team to find a resolution that satisfied the customer. By following up with the customer after the issue was resolved, I ensured their satisfaction and helped to maintain a positive relationship with them.", "professional"),
    Example("I have had numerous instances where I made sure a customer was satisfied with our service. One particular instance was when a customer contacted us regarding a billing issue. I was able to communicate effectively with the customer, address their concerns, and work with my team to resolve the issue in a timely manner. By providing updates and following up with the customer, I ensured that they were pleased with our service.", "neutral"),
    Example("I remember one time when a customer was really upset about a billing issue. I made sure to listen to their complaints and worked with my team to fix the problem. I kept them in the loop and checked back in to make sure they were happy with how we handled things. It ended up being all good!", "casual"),
    Example("During a client presentation, I was asked an unexpected question that required me to think on my feet. Without hesitation, I took a moment to gather my thoughts, provided a concise answer, and backed up my response with relevant data and examples. By being quick-witted and well-prepared, I was able to demonstrate my adaptability and problem-solving skills in front of the client.", "professional"),
    Example("I have had numerous instances where I needed to think on my feet. One particular instance was during a client meeting where I was asked a question that required a quick response. I was able to take a moment to gather my thoughts and provide a clear and concise answer that satisfied the client. By being able to adapt and think on my feet, I was able to maintain a professional image and handle unexpected situations effectively.", "neutral"),
    Example("There was this one time when I was in a meeting and got hit with a question I wasn't prepared for. But I didn't let it throw me off, I took a deep breath and came up with a quick answer that ended up being spot on. It was a bit nerve-wracking, but I was able to think on my feet and handle the situation.", "casual"),
    Example("One of my proudest professional accomplishments was successfully leading a team of individuals to complete a complex project within a tight deadline. This involved coordinating different departments, assigning tasks and responsibilities, monitoring progress, and ensuring that the final outcome met the client's requirements. Through effective communication, strong leadership skills, and attention to detail, I was able to exceed expectations and deliver a high-quality result that received positive feedback from both the client and senior management.", "professional"),
    Example("I have had several accomplishments in my professional career that I am proud of, but one that stands out is leading a team to complete a challenging project within a limited time frame. This involved delegating tasks, tracking progress, and coordinating with different departments to ensure that everything was on track. Despite some unforeseen setbacks, we were able to overcome them and complete the project on time, which received positive feedback from both the client and my supervisor.", "neutral"),
    Example("Man, there was this one project that I totally nailed. It was crazy difficult and we had a tight deadline, but I led the team like a boss and we pulled it off. I had to juggle a ton of tasks and communicate with different departments, but we got it done on time and the client loved it. It was a huge win and definitely one of my proudest moments in my career.", "casual")
]
